name: Sync to port2 repo

on:
  push:
    branches:
      - dev

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to port2 repo
        run: |
          git config --global user.name "sync-bot"
          git config --global user.email "sync@bot.com"

          # Add target repo as remote
          git remote add target https://${{ secrets.PORT_REPO_TOKEN }}@github.com/shivsh01/port2.git


         # Remove old files except .git
        cd target
        find . -mindepth 1 -not -path "./.git*" -delete

        # Copy files from source (excluding .github)
         rsync -av --exclude='.git' --exclude='.github' ../ ./


          # Push dev branch directly
          git push target HEAD:dev --force